"""ingestion and kb chunks

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 04:30:11.853961
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('object_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pipeline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pages_done', sa.Integer(), nullable=False),
    sa.Column('pages_total', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attachment_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('finished_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestions_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestions_sha256'), ['sha256'], unique=False)

    op.create_table('kb_chunks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kb_document_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['kb_document_id'], ['kb_documents.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_chunks_kb_document_id'), ['kb_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_chunks_object_id'), ['object_id'], unique=False)

    with op.batch_alter_table('kb_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='pending'))
        batch_op.add_column(sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kb_documents', schema=None) as batch_op:
        batch_op.drop_column('error')
        batch_op.drop_column('status')

    with op.batch_alter_table('kb_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_chunks_object_id'))
        batch_op.drop_index(batch_op.f('ix_kb_chunks_kb_document_id'))

    op.drop_table('kb_chunks')
    with op.batch_alter_table('ingestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestions_sha256'))
        batch_op.drop_index(batch_op.f('ix_ingestions_object_id'))

    op.drop_table('ingestions')
    # ### end Alembic commands ###
